[dev]
command = "npm run serve"
publish = "_site/"

[build]
publish = "_site/"
command = "npm run build"

[[redirects]]
from = "/vigenere/output/"
to = "/.netlify/functions/vigenere"
status = 200
force = true
_generated_by_eleventy_serverless = "vigenere"

[[redirects]]
from = "/caesar/output/"
to = "/.netlify/functions/caesar"
status = 200
force = true
_generated_by_eleventy_serverless = "caesar"

[[redirects]]
from = "/atbash/output/"
to = "/.netlify/functions/atbash"
status = 200
force = true
_generated_by_eleventy_serverless = "atbash"
