[dev]
command = "npm run serve"
publish = "_site/"

[build]
publish = "_site/"
command = "npm run build"

[[redirects]]
from = "/vigenere/output/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[[redirects]]
from = "/caesar/output/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[[redirects]]
from = "/atbash/output/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"
