[dev]
command = "npm run serve"
publish = "_site/"

[build]
publish = "_site/"
command = "npm run build"

[[redirects]]
from = "/ciphers/adfgvx/output/"
to = "/.netlify/functions/adfgvx"
status = 200
force = true
_generated_by_eleventy_serverless = "adfgvx"

[[redirects]]
from = "/ciphers/book/output/"
to = "/.netlify/functions/book"
status = 200
force = true
_generated_by_eleventy_serverless = "book"

[[redirects]]
from = "/ciphers/vigenere/output/"
to = "/.netlify/functions/vigenere"
status = 200
force = true
_generated_by_eleventy_serverless = "vigenere"

[[redirects]]
from = "/ciphers/caesar/output/"
to = "/.netlify/functions/caesar"
status = 200
force = true
_generated_by_eleventy_serverless = "caesar"

[[redirects]]
from = "/ciphers/atBash/output/"
to = "/.netlify/functions/atbash"
status = 200
force = true
_generated_by_eleventy_serverless = "atbash"

[[redirects]]
from = "/book"
to = "/ciphers/book"
status = 301
force = true

[[redirects]]
from = "/atbash"
to = "/ciphers/atbash"
status = 301
force = true

[[redirects]]
from = "/caesar"
to = "/ciphers/caesar"
status = 301
force = true

[[redirects]]
from = "/vigenere"
to = "/ciphers/vigenere"
status = 301
force = true
